### ISSUE TITLE
PSE historical data request.

### ISSUE THREAD

**Issue by faststare** [gremdev/pse#1]
boss, baka pwede mag-request ng additional api about sa pag-fetch ng pse historical stocks data.
pahirapan kasi pagkuha stock data sa pilipinas, kaya yung data scraping sa investagrams.com pero wala akong permission at limited lang yung pwede yung data na makukuha sa html pages nila. (o hindi pa ako gaano kagaling magparse ng html pages, advanced kasi masyado yung conditional parsing html pages)  at sa local brokerage ko naman, nakaprotect para sa html parsing bot kaya miski csv data sa broker ko, manual pa rin. -_- pero salamat sa api mo na to boss.
(disclaimer please kindly use google translate  if you are not filipino).

**Comment by gremdev** [comment]
boss, ang original na api na gamit ko ay nandito https://github.com/edgedalmacio/phisix  . may na implement ata na 1 year na historical data. nka pag scrape nman ako sa pse and edge kaso hindi ata legal mag scrape dun, tapos wla akong nakita na historical data dun na pede ma scrape.

**Comment by faststare** [comment]
hindi legal boss dun. may issues pa nga yung investagrams.com pag-release ng historical data chart. dahil umaalma yung mga local broker dito kasi milyones raw bayad kay pse sa data tapos yung nirelease raw ni investagrams ng libre. pero salamat sa api mo boss.
